name: Jenkins Security Scan
on:
  push:
    branches:
      - master
      - codeql-2.16.4
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  security-scan:
    uses: jenkins-infra/jenkins-security-scan/.github/workflows/jenkins-security-scan.yaml@main
    with:
      java-cache: maven
      java-version: 11
